[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = ["python3 -m pip install --break-system-packages -r requirements.txt"]

[phases.build]
cmds = ["python3 manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
